### ISSUE TITLE
regex error when running the code

### ISSUE THREAD

**Issue by alipazokit** [mkerin/LEMMA#8] opened 2022-06-01 03:03 UTC
Hi there,

I successfully compiled the code. However, when I tried to run the test file, I am getting the following error :

terminate called after throwing an instance of 'std::regex_error'   what():  regex_error

Although there was no issue in compiling step, I also tried to compile with different version of gcc like  gcc/4.9.5  gcc/5.3.0  gcc/7.5.0(default)  gcc/8.3.0   gcc/10.2.0  but it does not resolve the problem.

Appreciate your suggestions to solve this issue. thanks,

**Comment by alipazokit** [comment] 2022-06-03 06:17
I am just following up to check if you got some time to look at the issue
posted on github.


Ali

**Comment by mkerin** [comment] 2022-06-04 09:54
Hi Ali. Sorry, I have only just seen this. I will have time to take a look tomorrow... 

I suspect that being able to compare the compilation logs will be useful, so if you have these readily available I would appreciate it if you can upload them.

**Comment by alipazokit** [comment] 2022-06-04 20:19
Thank you !
Here are the files :
[CMakeCache.txt](https://github.com/mkerin/LEMMA/files/8838645/CMakeCache.txt)
[compile.lemma.log.txt](https://github.com/mkerin/LEMMA/files/8838646/compile.lemma.log.txt)

**Comment by mkerin** [comment] 2022-06-05 21:04
Hmm, I have tried recompiling LEMMA and rerunning the examples but I haven't managed to reproduce any errors. Could you be specific about what you mean exactly by the 'test file' / what input you are using to produce the error?

It would also be helpful if you could run the unit tests and let me know if they pass. You should be able to do this as follows
```
cd /u/home/a/alipazok/sriram/LEMMA/
cmake --build build --target tests -- -j 4 
cd build
ctest --output-on-failure

**Comment by alipazokit** [comment] 2022-06-05 22:30
I meant running the following based on [here](https://mkerin.github.io/LEMMA/gplemma/) : 
```
mpirun -n 1 build/lemma_1_0_3 \
  --gplemma --random-seed 1 \
  --pheno example/pheno.txt.gz \
  --streamBgen example/n5k_p20k_example.bgen \
  --environment example/env.txt.gz \
  --out example/gplemma.out.gz
```

**Comment by alipazokit** [comment] 2022-06-05 22:35
```
(base) [alipazok@login3 LEMMA]$ cmake --build build --target tests -- -j 4 
[100%] Built target tests
(base) [alipazok@login3 LEMMA]$ ctest --output-on-failure
Test project /u/home/a/alipazok/sriram/LEMMA
No tests were found!!!
(base) [alipazok@login3 LEMMA]$ 
```
can you share your machine's gcc and cmake versions?

**Comment by mkerin** [comment] 2022-06-06 20:58
I'm currently compiling on a Mac with Clang, but I'll retry with gcc.

Sorry - you need to `cd` into the build directory for the unit tests.. I have updated the original snippet.

Logs in case helpful:
[cmake.log](https://github.com/mkerin/LEMMA/files/8847952/cmake.log)
[CMakeCache.txt](https://github.com/mkerin/LEMMA/files/8847953/CMakeCache.txt)

**Comment by alipazokit** [comment] 2022-06-07 05:41
I run ctest in build dir, the output is attached. 
[ctest.txt](https://github.com/mkerin/LEMMA/files/8850342/ctest.txt)

In general, It seems there are some issues with different version of gcc and regular expressions.

**Comment by alipazokit** [comment] 2022-06-22 19:42
have you had a chance to run with gcc?  the problem is in line 448 of  parse_arguments.cpp where you are calling regex_replace

**Comment by mkerin** [comment] 2022-06-26 21:38
I managed to compile locally with GCC 11.3.0, but unfortunately could not reproduce the issue. I think the best way to proceed is just to get some CI running with a couple of compilers..  I’m working on this now but it may take some time as LEMMA is a weekend only project for me.

As a temporary solution to unblock your work, you could comment out lines 448-457 of parse_arguments.cpp. The use of std::regex is not important - it is just there to infer the number of VB iterations that have passed for a LEMMA checkpoint. If you actually need to restart from a checkpoint then it is possible to set the number of iterations manually via `—vb-iter-start`. However I believe you are just interested in using gplemma? In which case the regex is irrelevant for you.

**Comment by alipazokit** [comment] 2022-07-13 17:21
Thanks! we managed to run the software !

**Comment by mkerin** [comment] 2022-07-19 20:03
Great! Thank you for letting me know. I am still (slowly) iterating towards more robust testing / a cleaner install so I will leave this issue open for now.

**Comment by mkerin** [comment] 2022-09-24 03:22
Just for future reference - I have done some work in the latest release to make compilation cleaner, and also switched on CI to double check that it builds properly / tests pass on linux. To my knowledge this is now resolved, so I'm closing the issue.

**Closed as completed by mkerin** 2022-09-24 03:22 UTC
